[package]
name = "frostfeed"
version = "0.1.0"
edition = "2024"

[dependencies]
feed-rs = { version = "2.3.1", features = ["sanitize"] }
html-to-markdown-rs = "2.19.8"
iced = { version = "0.14.0", features = ["tokio", "markdown", "image"] }
lucide-icons = { version = "0.562.0", features = ["iced"] }
open = "5.3.3"
reqwest = { version = "0.13.1", features = ["gzip", "deflate", "brotli"] }

[features]
debug = ["iced/hot"]
